org: bearinmind
app: pdf-lambda-puppeteer
service: pdf-lambda-puppeteer

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
  prune:
    automatic: true
    number: 5

provider:
  name: aws
  runtime: nodejs14.x
  profile: default # Modify or remove accordingly
  region: eu-west-3
  endpointType: regional
  stage: ${opt:stage, 'dev'}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  buildReportPDF:
    handler: handler.buildReport
    memorySize: 1024 # Setting a higher RAM size to facilitate PDF generation
    events:
      - http:
          method: post
          path: /joint_reports/water_damage
      - http:
          method: get
          path: /joint_reports/water_damage/test

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline
